server:
  port: 9000

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/auth/realms/hybrid-service-realm
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: config-server-route
          uri: lb://config-server
          predicates:
            - Path=/config-server/**
          filters:
            - StripPrefix=1

        - id: user-service-users-route
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1

        - id: user-service-auth-route
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        - id: drivers-service-drivers-route
          uri: lb://drivers-service
          predicates:
            - Path=/api/drivers/**
          filters:
            - StripPrefix=1

        - id: admin-drivers-service-admin-drivers-route
          uri: lb://admin-drivers-service
          predicates:
            - Path=/api/admin/drivers/**
          filters:
            - StripPrefix=1

        - id: vehicle-service-vehicles-route
          uri: lb://vehicle-service
          predicates:
            - Path=/api/vehicles/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
