server:
  port: 9000
spring:
  application:
      name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/auth/realms/hybrid-service-realm
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: config-server-route
          uri: lb://config-server
          predicates:
            - Path=/config-server/actuator/**
          filters:
            - StripPrefix=1
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
