server:
  port: 8082
app:
  kafka:
    admin:
      auto-create: true
    topics:
      user-events: user.events.v1
      ride-request-event: ride.request.event.v1
      driver-rated-event: driver.rated.event.v1
      ride-accept-event: ride.accept.event.v1
      ride-reject-event: ride.reject.event.v1
      driver-assigned-ride-event: driver.assigned.ride.event.v1
spring:
  application:
    name: taxi-service
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      acks: all
      retries: 100
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        spring.json.type.mapping: >-
          ride-requested:com.rezende.taxi_service.dto.RideRequestedEventDTO,
          driver-rated:com.rezende.taxi_service.event.DriverRatedEvent,
          ride-accepted-by-driver:com.rezende.taxi_service.event.RideAcceptedByDriverEvent,
          ride-rejected-by-driver:com.rezende.taxi_service.event.RideRejectedByDriverEvent
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: "taxi-service-consumer-group"
      enable-auto-commit: false
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.type.mapping: driver-assigned-to-ride:com.rezende.taxi_service.dto.DriverAssignedToRideEventDTO
    listener:
      ack-mode: manual
      type: single
  datasource:
    url: jdbc:postgresql://taxi-db:5432/taxi_service_db
    username: ${POSTGRES_USERNAME_TAXI_SERVICE}
    password: ${POSTGRES_PASSWORD_TAXI_SERVICE}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
