server:
  port: 8082
app:
  kafka:
    admin:
      auto-create: true
    topics:
      user-events: taxi.events.v1
spring:
  application:
    name: taxi-service
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      acks: all
      retries: 100
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: "taxi-service-consumer-group"
      enable-auto-commit: false
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: 'com.rezende.user_service.events, com.rezende.driver_service.events, com.rezende.vehicle_service.events, com.rezende.taxi_service.events'
    listener:
      ack-mode: manual
      type: single
  datasource:
    url: jdbc:postgresql://taxi-db:5432/taxi_service_db
    username: ${POSTGRES_USERNAME_TAXI_SERVICE}
    password: ${POSTGRES_PASSWORD_TAXI_SERVICE}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
