server:
  port: 8081
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://user-db:5432/user_service_db
  data:
    redis:
      host: redis
      port: 6979
    cache:
      type: redis
      redis:
        time-to-live: 10m
        cache-names: keycloak-admin-token
    cache.cache-names: keycloak-admin-token
    spring.cache.redis.time-to-live.keycloak-admin-token:
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          keycloak-client:
            provider: keycloak
            client-id: my-client
            authorization-grant-type: password
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/auth/realms/hybrid-service-realm
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
keycloak:
  admin:
    server-url: http://keycloak:8080/auth
    realm: hybrid-service-realm
