server:
  port: 8083
app:
  kafka:
    admin:
      auto-create: true
    topics:
      vehicle-events: vehicle.events.v1
      approved-vehicle-event: approved.vehicle.event.v1
spring:
  application:
    name: vehicle-service
  datasource:
    url: jdbc:postgresql://vehicle-db:5432/vehicle_service_db
    username: ${POSTGRES_USERNAME_VEHICLE_SERVICE}
    password: ${POSTGRES_PASSWORD_VEHICLE_SERVICE}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migrations
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      acks: all
      retries: 100
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        spring.json.type.mapping: vehicle-approved:com.rezende.vehicle_service.events.VehicleApprovedEvent
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
